### ISSUE TITLE
Porn images issues

### ISSUE THREAD

**Issue by chunlaw** [chiuinan/chiuinan.github.io#1]
I found that there are several porn images from some 18+ old games. Would it be better to encode the image in base64 and hence they would not be displayed in Github or serve as a direct image download link in github.io?

Meanwhile, your work is great, I have been following the walkthrough for 仙劍奇俠傳. Good old days.

**Comment by chiuinan** [comment]
OK, I'll compress these images into 7z format in next update. It needs several days.
