### ISSUE TITLE
關於第三波出的信長之野望2中文版

### ISSUE THREAD

**Issue by coolhaken-1** [chiuinan/chiuinan.github.io#11]
這個遊戲不論是英文版或是中文版，應該都可以在 CGA 模式下執行。
資料庫中的版本，不但會額外顯示破解者的資訊，而且在 CGA 模式下會當機無法執行。
以下是沒有問題的版本，建議青杉兄比對並置換一下。
下載：https://1drv.ms/u/s!AiKJ-2AspwhCgQYky-fOIO54eeTA?e=HSQVjq

**Comment by chiuinan** [comment]
已修正
