### ISSUE TITLE
或許可以考慮精簡遊戲列表

### ISSUE THREAD

**Issue by danny0838** [chiuinan/chiuinan.github.io#21]
不曉得目前區分遊戲總表和遊戲簡表的目的？

簡表似乎是和總表相同，但只顯示中文遊戲名稱。不過比對後看起來二者有些順序不太一樣（例如總表最後是緋王傳2，簡表是龍騎士4），不曉得是有特殊用意或是誤植？

如果二者內容一樣，似乎更簡單的方法是只做總表，並且用JavaScript提供簡表顯示模式，這樣就不必每次都維護兩個表格。如果有意讓二者排序不同，也可以改成用JavaScript提供多種不同排序的功能（應該會有人希望能用名稱、評價、年代、大小等方式排序）。

類似的問題也在總表和分表。如果二者內容一樣，總表只是為了方便玩家搜尋，那應該可以只寫分表，並且用JavaScript實作總表檢視、甚至更精細的搜尋功能（如果沒要很講究，搜尋功能可以考慮直接嵌入Google介面或提供連結）。或者也可以反過來，只寫一個總表，用JavaScript實作分類檢視。

這樣應該比較符合DRY(don't repeat yourself)原則，日後也可以避免每次增加新遊戲或修改遊戲資訊都更新多個檔案。

**Comment by chiuinan** [comment]
其實簡表比較沒什麼意義, 只是我用來排序, 得知新遊戲應該放在總表的那個位置而已. 目前已從連結裡拿掉, 但還是放在裡面, 以備新增遊戲時排序使用.

簡表與總表之所以順序不同, 是因為最早時是用BIG5碼寫的, 所以排序時都用BIG5碼排, 後來放到Github, 只能接受utf-8編號, 於是變成以UNICODE排序, 順序便變得不一樣. 但總表已無法重新排序 (不然會花很多時間), 因此之前已按BIG5碼排好的就先將就著.

基本上我的網頁不希望加入script或外部搜尋. 其實最初目的是供網友打包下載, 玩遊戲時可在PC上直接參照, 因此並不打算考慮手機上觀看的問題. 所以你說的手機顯示問題, 其實我都興趣缺缺.

總表有必要存在. 因為有時新進遊戲我會直接在browser上搜尋該頁面, 馬上可以快速得知是否有介紹過, 以及類似名字或其他各代的遊戲

**Comment by danny0838** [comment]
有需要那麼排斥 script 嗎？XD

我試做了一個簡單的自動總表產生器，載入總表頁面 https://danny0838.github.io/chiuinan.github.io/game/game/list.htm 就會自動從 menu 載入各分表，並載入所有分表的內容結合成總表，GitHub Pages 的速度大概幾秒內可載入完成。點擊表頭可以排序該欄位，手機和 PC 操作起來速度都滿快的。

而對於不支援 JS 的電腦，頂多是不能看總表而已，各分表還是可以正常看。
