### ISSUE TITLE
網頁標準化

### ISSUE THREAD

**Issue by danny0838** [chiuinan/chiuinan.github.io#5]
目前以 HTML 撰寫的攻略多是使用較老舊的 HTML 語法，可能導致跨平台、跨瀏覽器的相容問題。不曉得您是否有意願調整？

1. 所有頁面均加上 `<!DOCTYPE html>`：缺少此宣告時，瀏覽器會用 quirk mode 解讀網頁，可能導致某些樣式以不符合標準的方式渲染。
2. 避免指定細明體、標楷體等字體：非 Windows 瀏覽器（如 Mac, Linux, 手機使用者）沒內建這些字體，無法正常顯示。
    細明體可改成 `<span style="font-family: monospace">` 或 `<span style="font-family: MingLiU, monospace">` 以確保使用等寬字體；標楷體可用 `<span style="font-family: DFKai-SB, monospace">` 或考慮改用其他 CSS 樣式呈現。
   進一步說，`<font ...>` 是 HTML5 棄用的 tag，一般建議改成對應的 `<span style=...>`。
   `<font size="X">` 可改成  `<span style=font-size: Y;">`，X 值 1~7 可分別對應 Y 值 `x-small`、`small`、`medium`、`large、x-large`、`xx-large`、`xxx-large`，但這些值在不同瀏覽器可能有不同設定，更建議換成用 px 為單位。
   如果是像 `<pre><font ...>...</font></pre>`  之類的情況，可改寫成 `<pre style="...">...</pre>`，或直接外掛 CSS 檔控制 `pre` 的樣式（可一個遊戲統一用一個 CSS）。

其他可以考慮優化的：
1. `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` 改成較精簡的 `<meta charset="utf-8">`
2. `<a name="...">` 也是 HTML5 棄用的寫法，一般可改寫成 `<a id="...">`。
    如果是像 `<td><a name="...">...</a></td>` 的情況，可改寫成 `<td id="...">...</td>`（如果是指向某列，直接寫在 tr 可能更好）。
3. `<center>` 是 HTML5 棄用的寫法，一般可改寫成 `<div style="text-align: center;">`。

這些大多可用多檔案尋找／取代處理。如果您有意願改，我或許也可以協助提 PR。

**Comment by chiuinan** [comment]
1.我的網頁風格是極簡風(keep it simple), 除非必要, html tag能少則少, script一律禁用. 所用的特殊排版只有表格table和條列ol, 基本上顯示出來不會有太大的差異, 所以quirk mode也無妨, 無需加上!doctype html
2.不要直接指明中文字體名, 這點我認同, 我會再加以修正.
3.字體大小與顏色, 我還是會用font tag, 以及center tag, 因為這些比較簡短. 我並不在乎一定要遵循HTML5
4.a name="..."改成id, 或與td, tr結合, 可以更加簡短, 這些我會採用
5.meta更短的寫法, 我也會採用
6.我的網頁不會有css檔或js檔, 目標就是任一個網頁都可獨立顯示.

我現在正在趕工作, 等告一段落後再來處理.
