### ISSUE TITLE
Tyrian2000 攻略

### ISSUE THREAD

**Issue by danny0838** [chiuinan/chiuinan.github.io#6]
4-8 Ice Secret 最後面可取得 `#41`。（不確定是否有隨機性，我用 Normal 難度拿 2 次都是）

![圖片](https://github.com/chiuinan/chiuinan.github.io/assets/531417/7070fceb-c811-4600-ae88-9ed1f3c22b07)

[特殊武器列表](http://chiuinan.github.io/game/game/intro/eng/e51/tyrian/tyrian/item.htm)描述`「#01～#06的特殊武器才能在Full Game裡取得」`可能需要調整，因為光是 Ice Secret 就能拿到 `#15` 和 `#41` 了。

[新手提示](http://chiuinan.github.io/game/game/intro/eng/e51/tyrian/tyrian/notes.htm)/武器選擇/特殊武器一節可能也需要調整。

**Comment by chiuinan** [comment]
謝謝告知. 當初我看到圖像和#15一樣, 就沒去拿取, 沒想到是#41

**Comment by danny0838** [comment]
看起來在 a48d94f1e1905c0c49337549a8636941b4677d46 已補上。
