### ISSUE TITLE
三國志 II 中文版的 bug ?

### ISSUE THREAD

**Issue by coolhaken-1** [chiuinan/chiuinan.github.io#7]
青杉兄，請教一下：
關於 DOS  版的 三國志 2，第三波最初是推出售價 NT$600 元的英文版，稍後才推出售價 NT$1200 元的中文版。
我發現在中文版的開頭動畫中，有一個地方的畫面有問題（CGA 模式）：
![open_005](https://github.com/chiuinan/chiuinan.github.io/assets/152180163/0a9c517a-ee03-4266-ab8a-74e734decf7f)
而在英文版中，它顯示如下：
![open_006](https://github.com/chiuinan/chiuinan.github.io/assets/152180163/aaecf720-ba20-4916-8991-3bf7140e4030)
個人感覺這是中文版在在這個地方放錯了圖片所致，不知能否麻煩您抽空研究看看能否將之修正？
另外，在第三波的英文版中有一個 R2HELP 的常駐程式，似乎可以線上翻譯，但我手上沒有使用手冊，不知如何使用。
您能幫忙追蹤一下該程式看看如何在遊戲中調用它嗎？
謝謝。

PS：
中文版的 三國志 2 在目前的 DOSBox 0.74-3 跑 EGA 模式會有問題，這個問題可以 boot 到真實 DOS 解決。
所以壓縮包中一併放了 S2C.IMG 這個可開機鏡像，直接在 DOSBox 中執行 "boot S2C.IMG" 即可。
檔案下載：https://1drv.ms/u/s!AiKJ-2AspwhCgQJQH3yKij1zr_-R?e=v4D3Yf

**Comment by chiuinan** [comment]
ok, 我登記下來, 再安排時間解決.
因為前面已排了不少, 初步估計要等半年到一年左右才能輪到. 請耐心等候, 謝謝.

**Comment by chiuinan** [comment]
先解決一個, 開頭動畫的問題要追比較久:
R2HELP: 進入遊戲後, 按右Shift+Ctrl啟用, 只能查三國志2裡出現的單字

另外, coolhaken兄是否有風火跳棋1,2(倚天)、三角跳棋(船塢資訊)、電腦跳棋專家(第三波), 這些古老的跳棋遊戲?

**Comment by chiuinan** [comment]
中文版確實少了一張圖, 從英文版補入, 並修正OPEN.EXE相關讀取資訊即可:
https://drive.google.com/file/d/1-9W7M17pYAhAJTBq17YM95PIDTXkCU8l/view?usp=drive_link
(Google區暫放一個月, 永久存放在OneDrive區)
