### ISSUE TITLE
關於1994年熊貓出的西遊記破解問題

### ISSUE THREAD

**Issue by coolhaken-1** [chiuinan/chiuinan.github.io#9]
之前在骨灰集散地和 walter 曾討論過這個遊戲的破解。
因為它需要撥殼，而且還有暗椿，破解並不容易。目前在網路上流傳的檔案都是破解不全的版本，
程式在 CS:4C4C 會有另外的檢查動作，如果只是簡單跳過密碼保護，遊戲會在某些地方發生問題。
以下的檔案是破解好的版本，其中的 WEST.E__ 是原始未撥殼未破解的檔案；WEST.EX_ 是已撥殼未破解的檔案；
而 WEST.EXE 則是撥殼完成且破解好的檔案。
下載：https://1drv.ms/u/s!AiKJ-2AspwhCgQVCLt_oQq4O1h6k?e=qQ8Uig
不過 walter 兄並沒有再深入追踨到破關，這部分可能還需要再測試 ( 如果青杉兄有空的話 )。
但目前這個版本應該是比較沒問題的版本，請青杉兄對照一下是否有必要更新資料庫中的檔案。

**Comment by chiuinan** [comment]
已更換

**Comment by chiuinan** [comment]
有網友反應破解碼仍有問題, 最後的結局動畫無法播放. 經檢測, 發現結局動畫除了必須困難度是Middle以上之外, 還必須進入過密碼輸入. 前述破解碼已略過密碼輸入, 所以會造成結局動畫無法播放. 只需將這個額外檢測拿掉即可:

      WEST.EXE
        3B 06 3E 16 75 03
        -- -- -- -- -- 00
        76 06 B8 02 00 E8 D9 00 E8 4D 03 2E 3B 1E 4C 4C 75 E5
        -- 09 -- -- -- -- -- -- -- -- -- -- 8B -- -- -- -- 00
